import { metadata } from './metadata'

describe('metadata', () => {
  it('has the correct title', () => {
    expect(metadata.title).toBe('Create Next App')
  })

  it('has the correct description', () => {
    expect(metadata.description).toBe('Generated by create next app')
  })
}) 